# Generated by Django 6.0 on 2026-04-30 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_hr_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreferences',
            name='email_digest',
            field=models.CharField(choices=[('none', 'Off'), ('daily', 'Daily'), ('weekly', 'Weekly')], default='daily', max_length=10),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='notify_announcements',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='notify_login_alert',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='notify_mentions',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='notify_report_approved',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='notify_report_rejected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='notify_task_assigned',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='notify_task_overdue',
            field=models.BooleanField(default=True),
        ),
    ]
