# Generated by Django 6.0 on 2026-05-03 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpreferences',
            name='theme',
            field=models.CharField(blank=True, default='ocean', max_length=30),
        ),
    ]
