# Generated by Django 6.0 on 2026-05-06 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_theme_field_free_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='account_type',
            field=models.CharField(choices=[('organization', 'Organization'), ('individual', 'Individual')], default='organization', max_length=20),
        ),
    ]
