# Generated by Django 6.0.4 on 2026-04-30 06:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyreport',
            name='place_of_work',
            field=models.CharField(default='Corporate Office', max_length=150),
        ),
        migrations.AlterField(
            model_name='taskentry',
            name='place_of_work',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.CreateModel(
            name='WorkLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('office', 'Office'), ('store', 'Store'), ('factory', 'Factory'), ('warehouse', 'Warehouse'), ('remote', 'Remote'), ('other', 'Other')], default='other', max_length=20)),
                ('icon', models.CharField(default='📍', max_length=10)),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_locations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_default', 'category', 'name'],
            },
        ),
    ]
