# Generated by Django 6.0.4 on 2026-05-01 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_alter_dailyreport_place_of_work_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskentry',
            name='ai_assisted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='taskentry',
            name='ai_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='taskentry',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
