# Generated by Django 6.0 on 2026-04-30 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0002_systemsettings_maintenance_mode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='company_logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/'),
        ),
    ]
