# Generated by Django 6.0.4 on 2026-05-01 12:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIProviderConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_key', models.CharField(choices=[('groq', 'Groq'), ('claude', 'Anthropic Claude'), ('openai', 'OpenAI'), ('gemini', 'Google Gemini'), ('ollama', 'Ollama (Local)'), ('custom', 'Custom Endpoint')], max_length=20)),
                ('display_name', models.CharField(max_length=100)),
                ('base_url', models.CharField(blank=True, default='', max_length=255)),
                ('model_name', models.CharField(max_length=100)),
                ('encrypted_api_key', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AIFeatureConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_key', models.CharField(max_length=40, unique=True)),
                ('display_name', models.CharField(max_length=100)),
                ('is_enabled', models.BooleanField(default=True)),
                ('custom_prompt_template', models.TextField(blank=True, default='', help_text='Optional. Use {input} as placeholder for user content.')),
                ('max_tokens', models.IntegerField(default=300)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fallback_provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fallback_features', to='ai_features.aiproviderconfig')),
                ('primary_provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_features', to='ai_features.aiproviderconfig')),
            ],
        ),
        migrations.CreateModel(
            name='AIUsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_key', models.CharField(max_length=40)),
                ('provider_key', models.CharField(max_length=20)),
                ('task_id', models.IntegerField(blank=True, null=True)),
                ('tokens_used', models.IntegerField(default=0)),
                ('latency_ms', models.IntegerField(default=0)),
                ('success', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_usage_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
